### PR TITLE
Fixed GetResultCode KeyNotFound exception 

### PR DESCRIPTION
**Pull request by Zubastic**
Fixed bug, when server returned unknown code for our library

### CODE REVIEW

**Comment by Zubastic** [comment]
Also fixed ReferralFollowing setting.

**Review by mkostreba — APPROVED** [review]
Thank you.

**Review by mkostreba — COMMENTED** [review]
By going with NLog, hard-coded, I feel like we are imposing an opinionated logging option on all users. In my day to day work, I use serilog.
I would be inclined to add this if we implemented a provider pattern that made it possible for users to implement the logging framework of their choice.

**Review by mkostreba — APPROVED** [review]
Clean up is always Good!

**Review by mkostreba — APPROVED** [review]
Thank you!

**Review by mkostreba — APPROVED** [review]

**Pull request merged**
